import React, { useEffect, useState, useRef } from "react";
import Head from "next/head";

import Header from "../components/Header";
import Loading from "../components/Loading";
import Navbar from "../components/Navbar";
import Work from "../components/Work";
import About from "../components/About";

export default function Home({ loading }) {
  return (
    <div className="relative">
      <Head>
        <title>Mike | Software engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <Loading />}
      <>
        <Navbar />
        <Header loading={loading} />
        <Work />
        <About />
      </>
    </div>
  );
}
